
server:
  port: 8088
  max-http-header-size: 16000
logging:
  level:
    org:
      springframework=DEBUG:
spring:
  application:
    name: file-importer
  datasource:
    url: jdbc:postgresql://localhost:5432/importer_database?currentSchema=file_importer_schema,public;
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: UTC
          batch_size: 25
          batch_versioned_data: true
        default_batch_fetch_size: 25
        batch_fetch_style: PADDED
        order_inserts: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: development, production
    default-schema: file_importer_schema

crypto-compare:
  api-key: 53bdd104b9bb83f976930c67a45bf29bf7f8d3f9808ab350aa742f45a505417d

# App Properties
app:
  jwtSecret: =============javasecuritySecureRandom=============
  jwtExpirationMs: 86400000