version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres-contenedor-test
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=facundo
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=user1
      - APP_DB_PASS=passuser1
      - APP_DB_NAME=testdb
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
